// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: protos/foo.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace GrpcLibrary {
  public static partial class GrpcService1
  {
    static readonly string __ServiceName = "GrpcLibrary.GrpcService1";

    static readonly grpc::Marshaller<global::GrpcLibrary.HelloRequest1> __Marshaller_GrpcLibrary_HelloRequest1 = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::GrpcLibrary.HelloRequest1.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::GrpcLibrary.HelloResponse1> __Marshaller_GrpcLibrary_HelloResponse1 = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::GrpcLibrary.HelloResponse1.Parser.ParseFrom);

    static readonly grpc::Method<global::GrpcLibrary.HelloRequest1, global::GrpcLibrary.HelloResponse1> __Method_Test1 = new grpc::Method<global::GrpcLibrary.HelloRequest1, global::GrpcLibrary.HelloResponse1>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Test1",
        __Marshaller_GrpcLibrary_HelloRequest1,
        __Marshaller_GrpcLibrary_HelloResponse1);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::GrpcLibrary.FooReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of GrpcService1</summary>
    [grpc::BindServiceMethod(typeof(GrpcService1), "BindService")]
    public abstract partial class GrpcService1Base
    {
      public virtual global::System.Threading.Tasks.Task<global::GrpcLibrary.HelloResponse1> Test1(global::GrpcLibrary.HelloRequest1 request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for GrpcService1</summary>
    public partial class GrpcService1Client : grpc::ClientBase<GrpcService1Client>
    {
      /// <summary>Creates a new client for GrpcService1</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public GrpcService1Client(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for GrpcService1 that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public GrpcService1Client(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected GrpcService1Client() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected GrpcService1Client(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::GrpcLibrary.HelloResponse1 Test1(global::GrpcLibrary.HelloRequest1 request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Test1(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::GrpcLibrary.HelloResponse1 Test1(global::GrpcLibrary.HelloRequest1 request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Test1, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::GrpcLibrary.HelloResponse1> Test1Async(global::GrpcLibrary.HelloRequest1 request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Test1Async(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::GrpcLibrary.HelloResponse1> Test1Async(global::GrpcLibrary.HelloRequest1 request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Test1, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override GrpcService1Client NewInstance(ClientBaseConfiguration configuration)
      {
        return new GrpcService1Client(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(GrpcService1Base serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_Test1, serviceImpl.Test1).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, GrpcService1Base serviceImpl)
    {
      serviceBinder.AddMethod(__Method_Test1, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::GrpcLibrary.HelloRequest1, global::GrpcLibrary.HelloResponse1>(serviceImpl.Test1));
    }

  }
}
#endregion
