// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: protos/HelloWorld.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace GrpcLibrary {
  public static partial class GrpcService
  {
    static readonly string __ServiceName = "GrpcLibrary.GrpcService";

    static readonly grpc::Marshaller<global::GrpcLibrary.HelloRequest> __Marshaller_GrpcLibrary_HelloRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::GrpcLibrary.HelloRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::GrpcLibrary.HelloResponse> __Marshaller_GrpcLibrary_HelloResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::GrpcLibrary.HelloResponse.Parser.ParseFrom);

    static readonly grpc::Method<global::GrpcLibrary.HelloRequest, global::GrpcLibrary.HelloResponse> __Method_SayHello = new grpc::Method<global::GrpcLibrary.HelloRequest, global::GrpcLibrary.HelloResponse>(
        grpc::MethodType.ServerStreaming,
        __ServiceName,
        "SayHello",
        __Marshaller_GrpcLibrary_HelloRequest,
        __Marshaller_GrpcLibrary_HelloResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::GrpcLibrary.HelloWorldReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of GrpcService</summary>
    [grpc::BindServiceMethod(typeof(GrpcService), "BindService")]
    public abstract partial class GrpcServiceBase
    {
      public virtual global::System.Threading.Tasks.Task SayHello(global::GrpcLibrary.HelloRequest request, grpc::IServerStreamWriter<global::GrpcLibrary.HelloResponse> responseStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for GrpcService</summary>
    public partial class GrpcServiceClient : grpc::ClientBase<GrpcServiceClient>
    {
      /// <summary>Creates a new client for GrpcService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public GrpcServiceClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for GrpcService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public GrpcServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected GrpcServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected GrpcServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual grpc::AsyncServerStreamingCall<global::GrpcLibrary.HelloResponse> SayHello(global::GrpcLibrary.HelloRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SayHello(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncServerStreamingCall<global::GrpcLibrary.HelloResponse> SayHello(global::GrpcLibrary.HelloRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncServerStreamingCall(__Method_SayHello, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override GrpcServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new GrpcServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(GrpcServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_SayHello, serviceImpl.SayHello).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, GrpcServiceBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_SayHello, serviceImpl == null ? null : new grpc::ServerStreamingServerMethod<global::GrpcLibrary.HelloRequest, global::GrpcLibrary.HelloResponse>(serviceImpl.SayHello));
    }

  }
}
#endregion
